
//rsc
import React from 'react';

export const metadata = {
  title: "InstallattionNextJsApp",
  description: "Generated by create next app",
};


const page = () => {
    return (
        <div>
            installation page
        </div>
    );
};

export default page;